version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: ${CONTAINER_NAME} #my-server
    ports:
      # .env 파일의 변수를 사용하여 포트 매핑을 동적으로 설정
      - "${SERVER_PORT}:${SERVER_PORT}" #"9000:9000"
    environment:
      # .env 파일의 변수를 컨테이너 내부 환경 변수로 전달
      - HOST=${SERVER_HOST} #0.0.0.0
      - PORT=${SERVER_PORT} #9000
    # 포트는 외부에 직접 노출하지 않습니다. Nginx를 통해서만 통신합니다.

  # Nginx 리버스 프록시
  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"    # HTTP (인증서 발급용)
      - "443:443"  # HTTPS (메인 서비스용)
    volumes:
      # 작성한 Nginx 설정을 컨테이너에 연결
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Let's Encrypt 인증서 파일을 저장할 공간 연결
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server # server 컨테이너가 먼저 실행되도록 보장

  # Certbot (인증서 발급 및 갱신용)
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
