version: '3'

services:
  server: 
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "${APP_PORT}:8000"

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./self-signed-nginx.conf:/etc/nginx/conf.d/self-signed-nginx.conf
      - ./certs/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./certs/server.key:/etc/nginx/ssl/server.key:ro
    entrypoint: /bin/sh -c "envsubst '\$NGINX_PORT \$APP_PORT' < /etc/nginx/conf.d/self-signed-nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - server
